export const ADD_ELEMENT_START = "ADD_ELEMENT_START";
export const ADD_ELEMENT_SUCCESS = "ADD_ELEMENT_SUCCESS";
export const ADD_ELEMENT_ERROR = "ADD_ELEMENT_ERROR";

export const REMOVE_ELEMENT = "REMOVE_ELEMENT";

export const ADD_CART_ITEM = "ADD_CART_ITEM";
